import type { HobbyMeta } from '../types';

export const HOBBY_META: HobbyMeta[] = [
  {
    slug: 'gardening',
    name: 'Gardening',
    icon: '🌱',
    supportedMotivations: ['stress-relief', 'mindfulness', 'creativity', 'skill-building', 'fun'],
    minTimeMinutes: 60,
    learningStyles: ['reading', 'projects', 'video'],
    costLevel: 'low',
    environmentNeeds: 'both',
    socialNature: 'solo',
    intensityLevel: 'gentle',
    beginnerFriendly: true,
  },
  {
    slug: 'fitness-yoga',
    name: 'Fitness & Yoga',
    icon: '🧘',
    supportedMotivations: ['fitness', 'stress-relief', 'mindfulness', 'skill-building', 'fun'],
    minTimeMinutes: 90,
    learningStyles: ['video', 'community', 'projects'],
    costLevel: 'free',
    environmentNeeds: 'both',
    socialNature: 'both',
    intensityLevel: 'moderate',
    beginnerFriendly: true,
  },
  {
    slug: 'cooking-baking',
    name: 'Cooking & Baking',
    icon: '🍳',
    supportedMotivations: ['creativity', 'skill-building', 'social', 'fun', 'mindfulness'],
    minTimeMinutes: 60,
    learningStyles: ['video', 'projects', 'reading'],
    costLevel: 'low',
    environmentNeeds: 'indoor',
    socialNature: 'both',
    intensityLevel: 'gentle',
    beginnerFriendly: true,
  },
  {
    slug: 'photography',
    name: 'Photography',
    icon: '📸',
    supportedMotivations: ['creativity', 'skill-building', 'career', 'fun', 'social'],
    minTimeMinutes: 120,
    learningStyles: ['video', 'reading', 'projects'],
    costLevel: 'medium',
    environmentNeeds: 'both',
    socialNature: 'both',
    intensityLevel: 'gentle',
    beginnerFriendly: true,
  },
  {
    slug: 'creative-arts',
    name: 'Creative Arts',
    icon: '🎨',
    supportedMotivations: ['creativity', 'stress-relief', 'mindfulness', 'skill-building', 'fun'],
    minTimeMinutes: 60,
    learningStyles: ['video', 'projects', 'reading'],
    costLevel: 'low',
    environmentNeeds: 'indoor',
    socialNature: 'solo',
    intensityLevel: 'gentle',
    beginnerFriendly: true,
  },
  {
    slug: 'music',
    name: 'Music',
    icon: '🎵',
    supportedMotivations: ['creativity', 'skill-building', 'social', 'fun', 'stress-relief'],
    minTimeMinutes: 120,
    learningStyles: ['video', 'community', 'projects'],
    costLevel: 'low',
    environmentNeeds: 'indoor',
    socialNature: 'both',
    intensityLevel: 'moderate',
    beginnerFriendly: true,
  },
];
